return {
	"Screenshake",
	"Zane's Aimbot",
	"Quickbar",
	"Chat Tag",
	"VehicleSeat Commands",
	"Smallest Server Hop",
	"Biggest Server Hop",
	"AutoComplete",
	"Spectate GUI",
	"Facefuck",
	"IYCleanUp",
	"BetterNotifySize",
	"Neckbreaker",
	"SpecificDance",
	"Tween Flight",
	"Backpack Viewer",
	"Hug Tool",
	"Beyblade",
	"BringModel"
}
